//
//  Dingbatz.h
//
//  Automatically generated by DingBot 2019-10-31T15:23:53+01:00
//  NOTE: Do not edit this file manually!
//

#import <Foundation/Foundation.h>

@interface Dingbatz : NSObject



// Symbols
+ (NSString *)DingbatPiechart;
+ (NSString *)DingbatShutdown;
+ (NSString *)DingbatEdit;
+ (NSString *)DingbatPerson;
+ (NSString *)DingbatPeople;
+ (NSString *)DingbatHome;
+ (NSString *)DingbatBank;
+ (NSString *)DingbatCard;
+ (NSString *)DingbatOnlinePay;

+ (NSString *)DingbatMultiplePayments;
+ (NSString *)DingbatCoins;
+ (NSString *)DingbatEmail;
+ (NSString *)DingbatPosition;
+ (NSString *)DingbatReceipt;
+ (NSString *)DingbatCog;
+ (NSString *)DingbatHeart;
+ (NSString *)DingbatMapPin;
+ (NSString *)DingbatSettings;
+ (NSString *)DingbatBulletList;
+ (NSString *)DingbatTag;
+ (NSString *)DingbatShoppingCart;
+ (NSString *)DingbatDate;
+ (NSString *)DingbatStar;

+ (NSString *)DingbatTrash;
+ (NSString *)DingbatChat;
+ (NSString *)DingbatNotification;
+ (NSString *)DingbatShoppingBag;
+ (NSString *)DingbatLock;
+ (NSString *)DingbatUnlocked;
+ (NSString *)DingbatShowPassword;
+ (NSString *)DingbatHidePassword;
+ (NSString *)DingbatDelivery;
+ (NSString *)DingbatChip;
+ (NSString *)DingbatVolume;
+ (NSString *)DingbatIdea;
+ (NSString *)DingbatIdentityCard;
+ (NSString *)DingbatCloud;
+ (NSString *)DingbatChatDisabled;
+ (NSString *)DingbatHideKeyboard;
+ (NSString *)DingbatBackspace;
+ (NSString *)DingbatLibrary;
+ (NSString *)Dingbat123;
+ (NSString *)DingbatBarcode;
+ (NSString *)DingbatBarcodeOK;
+ (NSString *)DingbatSend;
+ (NSString *)DingbatSearch;
+ (NSString *)DingbatZoomIn;
+ (NSString *)DingbatZoomOut;
+ (NSString *)DingbatShareAndroid;
+ (NSString *)DingbatShare;
+ (NSString *)DingbatPDF;
+ (NSString *)DingbatLetter;
+ (NSString *)DingbatLetterRevert;
+ (NSString *)DingbatStoreOpen;
+ (NSString *)DingbatStoreClosed;
+ (NSString *)DingbatImagePlaceholder;
+ (NSString *)DingbatGift;

// Simple & Arrows
+ (NSString *)DingbatMenu;
+ (NSString *)DingbatTick;
+ (NSString *)DingbatCross;
+ (NSString *)DingbatBarDiagram;
+ (NSString *)DingbatPlus;
+ (NSString *)DingbatMinus;
+ (NSString *)DingbatReloadDouble;
+ (NSString *)DingbatRevert;
+ (NSString *)DingbatUndo;
+ (NSString *)DingbatVerticalEllipsis;
+ (NSString *)DingbatArrowRight;
+ (NSString *)DingbatArrowDown;
+ (NSString *)DingbatArrowLeft;
+ (NSString *)DingbatArrowUp;
+ (NSString *)DingbatSimpleArrowRight;
+ (NSString *)DingbatSimpleArrowDown;
+ (NSString *)DingbatSimpleArrowLeft;
+ (NSString *)DingbatSimpleArrowUp;
+ (NSString *)DingbatDownload;
+ (NSString *)DingbatImport;
+ (NSString *)DingbatExport;
+ (NSString *)DingbatPercent;

// Hardware
+ (NSString *)DingbatCardReaderOne;
+ (NSString *)DingbatCardReaderOneDisconnected;
+ (NSString *)DingbatAudioReader;
+ (NSString *)DingbatAudioReaderDisconnected;
+ (NSString *)DingbatMiura;
+ (NSString *)DingbatMiuraDisconnected;
+ (NSString *)DingbatXAC50;
+ (NSString *)DingbatXAC50Disconnected;
+ (NSString *)DingbatPhone;
+ (NSString *)DingbatTablet;
+ (NSString *)DingbatLaptop;
+ (NSString *)DingbatCamera;
+ (NSString *)DingbatCameraSwitch;
+ (NSString *)DingbatHeadphones;
+ (NSString *)DingbatMicrophone;
+ (NSString *)DingbatCashDrawer;
+ (NSString *)DingbatWiFi;
+ (NSString *)DingbatWiFiDisabled;

+ (NSString *)DingbatReceiptPrinter;
+ (NSString *)DingbatAudioCable;
+ (NSString *)DingbatPeripherals;
+ (NSString *)DingbatBatteryEmpty;
+ (NSString *)DingbatBatteryOneBar;
+ (NSString *)DingbatBatteryTwoBars;
+ (NSString *)DingbatBatteryThreeBar;
+ (NSString *)DingbatBatteryCharging;
+ (NSString *)DingbatBatteryCritical;
+ (NSString *)DingbatButtonOK;
+ (NSString *)DingbatButtonCancel;

// Circles
+ (NSString *)DingbatCircleTick;
+ (NSString *)DingbatCircledPlus;
+ (NSString *)DingbatCircledCross;
+ (NSString *)DingbatClock;
+ (NSString *)DingbatCircledWarning;
+ (NSString *)DingbatHelp;
+ (NSString *)DingbatInfo;
+ (NSString *)DingbatCompass;
+ (NSString *)DingbatHappy;
+ (NSString *)DingbatSad;
+ (NSString *)DingbatDead;
+ (NSString *)DingbatCircledMinus;
+ (NSString *)DingbatDenied;

// Digits
+ (NSString *)DingbatNumberZero;
+ (NSString *)DingbatNumberOne;
+ (NSString *)DingbatNumberTwo;
+ (NSString *)DingbatNumberThree;
+ (NSString *)DingbatNumberFour;
+ (NSString *)DingbatNumberFive;
+ (NSString *)DingbatNumberSix;
+ (NSString *)DingbatNumberSeven;
+ (NSString *)DingbatNumberEight;
+ (NSString *)DingbatNumberNine;

// Other
+ (NSString *)DingbatPlay;
+ (NSString *)DingbatPause;
+ (NSString *)DingbatTemplateCircle;
+ (NSString *)DingbatMenuBold;
+ (NSString *)DingbatGridSmall;
+ (NSString *)DingbatGridMedium;
+ (NSString *)DingbatGridLarge;
+ (NSString *)DingbatReorder;
+ (NSString *)DingbatCircleCrossFill;
+ (NSString *)DingbatCircleTickFill;
+ (NSString *)DingbatCircleOutline;

// Logos
+ (NSString *)DingbatIZettle;
+ (NSString *)DingbatIZettleSmall;
+ (NSString *)DingbatIZettleNegative;
+ (NSString *)DingbatIZettleIcon;
+ (NSString *)DingbatFacebook;
+ (NSString *)DingbatTwitter;
+ (NSString *)DingbatGooglePlus;
+ (NSString *)DingbatInstagram;
+ (NSString *)DingbatLinkedIn;
+ (NSString *)DingbatApple;
+ (NSString *)DingbatAndroid;
+ (NSString *)DingbatBluetoothLogo;
+ (NSString *)DingbatNFC;
+ (NSString *)DingbatApplePay;
+ (NSString *)DingbatContactless;
+ (NSString *)DingbatAndroidPay;
+ (NSString *)DingbatSamsungPay;
+ (NSString *)DingbatKlarna;
+ (NSString *)DingbatPayPal;
+ (NSString *)DingbatSwish;
+ (NSString *)DingbatSkatteverketLogo;
+ (NSString *)DingbatMasterCard;
+ (NSString *)DingbatMaestro;
+ (NSString *)DingbatMasterCardFull;
+ (NSString *)DingbatAmex;
+ (NSString *)DingbatVisa;
+ (NSString *)DingbatElectron;
+ (NSString *)DingbatVPay;
+ (NSString *)DingbatCarteBleue;
+ (NSString *)DingbatDiners;
+ (NSString *)DingbatJCB;
+ (NSString *)DingbatDiscover;
+ (NSString *)DingbatEC;
+ (NSString *)DingbatELV;
+ (NSString *)DingbatChinaUnionPay;
+ (NSString *)DingbatCarnetLogo;
+ (NSString *)DingbatELO;
+ (NSString *)DingbatVipps;
+ (NSString *)DingbatMobilePay;
+ (NSString *)DingbatHiper;
+ (NSString *)DingbatHipercard;

// Helpers
+ (NSString *)dingbatForCardName:(NSString*)cardName;
+ (NSString *)dingbatConstantForCardName:(NSString*)cardName;

@end