name: Add owner

on: workflow_dispatch

jobs:
  cocoapods_add_owner:
    runs-on: macos-12
    environment: "Cocoapods Add Owner"
    steps:
      - name: Checkout Repository
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
      - name: Install gem dependencies
        run:  gem install bundler && bundle install
      - name: Upload to Cocoapods
        env:
          REPO_NAME: ${{ github.repository }}
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
        run: bundle exec fastlane ios cocoapods_add_user