name: Validate Release

on:
  push: 
    branches: 
      - sdk-release-v*

jobs:
  build_sample_app:
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
      - name: Install gem dependencies
        run: gem install bundler && bundle install
      - name: Build Sample App
        run: bundle exec fastlane ios build_sample_app

  validate-changelog:
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
      - name: Install gem dependencies
        run: gem install bundler && bundle install
      - name: Check if the latest version is present in CHANGES
        run: bundle exec fastlane ios check_changelog

  validate-podspec:
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
      - name: Install gem dependencies
        run: gem install bundler && bundle install
      - name: Check if the latest version is present in .podspec file
        run: bundle exec fastlane ios check_podspec